services:
  gateway:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-gateway:latest
    build:
      dockerfile: src/Pb.ApiGateway/Dockerfile
      context: .
    ports:
      - 5000:80
    depends_on:
      - search
      - profile
  search:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-search:latest
    build: 
      dockerfile: src/Pb.Search.Service/Dockerfile
      context: .
    depends_on:
      - geo
      - rate
  profile:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-profile:latest
    build:
      dockerfile: src/Pb.Profile.Service/Dockerfile
      context: .
  geo:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-geo:latest
    build:
      dockerfile: src/Pb.Geo.Service/Dockerfile
      context: .
  rate:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-rate:latest
    build:
      dockerfile: src/Pb.Rate.Service/Dockerfile
      context: .