on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: actions-hub/docker/cli@master
        name: Use Docker-CLI
        env:
          SKIP_LOGIN: true

      - name: Build & Push
        run: |
          sudo docker login ${{ env.REGISTRY }} -u ${{ secrets.GH_PACKAGE_ACCOUNT }} -p ${{ secrets.GH_PACKAGE_TOKEN }}
          sudo docker-compose build
          sudo docker-compose push
          sudo docker logout ${{ env.REGISTRY }}